/**
 * Generated by apidoc - http://www.apidoc.me
 * Service version: 0.0.1
 * apidoc:0.11.76 http://www.apidoc.me/speedwing/pagerduty-api/0.0.1/play_2_5_client
 */
package speedwing.pagerduty.api.v0.models {

  case class CreateEvent(
    serviceKey: String,
    eventType: speedwing.pagerduty.api.v0.models.EventType,
    incidentKey: _root_.scala.Option[String] = None,
    description: _root_.scala.Option[String] = None,
    details: _root_.scala.Option[_root_.play.api.libs.json.JsObject] = None,
    client: _root_.scala.Option[String] = None,
    clientUrl: _root_.scala.Option[String] = None,
    contexts: _root_.scala.Option[_root_.play.api.libs.json.JsObject] = None
  )

  case class Result(
    status: String,
    message: String,
    incidentKey: String
  )

  sealed trait EventType

  object EventType {

    case object Trigger extends EventType { override def toString = "trigger" }
    case object Acknowledge extends EventType { override def toString = "acknowledge" }
    case object Resolve extends EventType { override def toString = "resolve" }

    /**
     * UNDEFINED captures values that are sent either in error or
     * that were added by the server after this library was
     * generated. We want to make it easy and obvious for users of
     * this library to handle this case gracefully.
     *
     * We use all CAPS for the variable name to avoid collisions
     * with the camel cased values above.
     */
    case class UNDEFINED(override val toString: String) extends EventType

    /**
     * all returns a list of all the valid, known values. We use
     * lower case to avoid collisions with the camel cased values
     * above.
     */
    val all = Seq(Trigger, Acknowledge, Resolve)

    private[this]
    val byName = all.map(x => x.toString.toLowerCase -> x).toMap

    def apply(value: String): EventType = fromString(value).getOrElse(UNDEFINED(value))

    def fromString(value: String): _root_.scala.Option[EventType] = byName.get(value.toLowerCase)

  }

}

package speedwing.pagerduty.api.v0.models {

  package object json {
    import play.api.libs.json.__
    import play.api.libs.json.JsString
    import play.api.libs.json.Writes
    import play.api.libs.functional.syntax._
    import speedwing.pagerduty.api.v0.models.json._

    private[v0] implicit val jsonReadsUUID = __.read[String].map(java.util.UUID.fromString)

    private[v0] implicit val jsonWritesUUID = new Writes[java.util.UUID] {
      def writes(x: java.util.UUID) = JsString(x.toString)
    }

    private[v0] implicit val jsonReadsJodaDateTime = __.read[String].map { str =>
      import org.joda.time.format.ISODateTimeFormat.dateTimeParser
      dateTimeParser.parseDateTime(str)
    }

    private[v0] implicit val jsonWritesJodaDateTime = new Writes[org.joda.time.DateTime] {
      def writes(x: org.joda.time.DateTime) = {
        import org.joda.time.format.ISODateTimeFormat.dateTime
        val str = dateTime.print(x)
        JsString(str)
      }
    }

    implicit val jsonReadsPagerdutyApiEventType = new play.api.libs.json.Reads[speedwing.pagerduty.api.v0.models.EventType] {
      def reads(js: play.api.libs.json.JsValue): play.api.libs.json.JsResult[speedwing.pagerduty.api.v0.models.EventType] = {
        js match {
          case v: play.api.libs.json.JsString => play.api.libs.json.JsSuccess(speedwing.pagerduty.api.v0.models.EventType(v.value))
          case _ => {
            (js \ "value").validate[String] match {
              case play.api.libs.json.JsSuccess(v, _) => play.api.libs.json.JsSuccess(speedwing.pagerduty.api.v0.models.EventType(v))
              case err: play.api.libs.json.JsError => err
            }
          }
        }
      }
    }

    def jsonWritesPagerdutyApiEventType(obj: speedwing.pagerduty.api.v0.models.EventType) = {
      play.api.libs.json.JsString(obj.toString)
    }

    def jsObjectEventType(obj: speedwing.pagerduty.api.v0.models.EventType) = {
      play.api.libs.json.Json.obj("value" -> play.api.libs.json.JsString(obj.toString))
    }

    implicit def jsonWritesPagerdutyApiEventType: play.api.libs.json.Writes[EventType] = {
      new play.api.libs.json.Writes[speedwing.pagerduty.api.v0.models.EventType] {
        def writes(obj: speedwing.pagerduty.api.v0.models.EventType) = {
          jsonWritesPagerdutyApiEventType(obj)
        }
      }
    }

    implicit def jsonReadsPagerdutyApiCreateEvent: play.api.libs.json.Reads[CreateEvent] = {
      (
        (__ \ "service_key").read[String] and
        (__ \ "event_type").read[speedwing.pagerduty.api.v0.models.EventType] and
        (__ \ "incident_key").readNullable[String] and
        (__ \ "description").readNullable[String] and
        (__ \ "details").readNullable[_root_.play.api.libs.json.JsObject] and
        (__ \ "client").readNullable[String] and
        (__ \ "client_url").readNullable[String] and
        (__ \ "contexts").readNullable[_root_.play.api.libs.json.JsObject]
      )(CreateEvent.apply _)
    }

    def jsObjectCreateEvent(obj: speedwing.pagerduty.api.v0.models.CreateEvent) = {
      play.api.libs.json.Json.obj(
        "service_key" -> play.api.libs.json.JsString(obj.serviceKey),
        "event_type" -> play.api.libs.json.JsString(obj.eventType.toString)
      ) ++ (obj.incidentKey match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("incident_key" -> play.api.libs.json.JsString(x))
      }) ++
      (obj.description match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("description" -> play.api.libs.json.JsString(x))
      }) ++
      (obj.details match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("details" -> x)
      }) ++
      (obj.client match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("client" -> play.api.libs.json.JsString(x))
      }) ++
      (obj.clientUrl match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("client_url" -> play.api.libs.json.JsString(x))
      }) ++
      (obj.contexts match {
        case None => play.api.libs.json.Json.obj()
        case Some(x) => play.api.libs.json.Json.obj("contexts" -> x)
      })
    }

    implicit def jsonWritesPagerdutyApiCreateEvent: play.api.libs.json.Writes[CreateEvent] = {
      new play.api.libs.json.Writes[speedwing.pagerduty.api.v0.models.CreateEvent] {
        def writes(obj: speedwing.pagerduty.api.v0.models.CreateEvent) = {
          jsObjectCreateEvent(obj)
        }
      }
    }

    implicit def jsonReadsPagerdutyApiResult: play.api.libs.json.Reads[Result] = {
      (
        (__ \ "status").read[String] and
        (__ \ "message").read[String] and
        (__ \ "incident_key").read[String]
      )(Result.apply _)
    }

    def jsObjectResult(obj: speedwing.pagerduty.api.v0.models.Result) = {
      play.api.libs.json.Json.obj(
        "status" -> play.api.libs.json.JsString(obj.status),
        "message" -> play.api.libs.json.JsString(obj.message),
        "incident_key" -> play.api.libs.json.JsString(obj.incidentKey)
      )
    }

    implicit def jsonWritesPagerdutyApiResult: play.api.libs.json.Writes[Result] = {
      new play.api.libs.json.Writes[speedwing.pagerduty.api.v0.models.Result] {
        def writes(obj: speedwing.pagerduty.api.v0.models.Result) = {
          jsObjectResult(obj)
        }
      }
    }
  }
}

package speedwing.pagerduty.api.v0 {

  object Bindables {

    import play.api.mvc.{PathBindable, QueryStringBindable}
    import org.joda.time.{DateTime, LocalDate}
    import org.joda.time.format.ISODateTimeFormat
    import speedwing.pagerduty.api.v0.models._

    // Type: date-time-iso8601
    implicit val pathBindableTypeDateTimeIso8601 = new PathBindable.Parsing[org.joda.time.DateTime](
      ISODateTimeFormat.dateTimeParser.parseDateTime(_), _.toString, (key: String, e: _root_.java.lang.Exception) => s"Error parsing date time $key. Example: 2014-04-29T11:56:52Z"
    )

    implicit val queryStringBindableTypeDateTimeIso8601 = new QueryStringBindable.Parsing[org.joda.time.DateTime](
      ISODateTimeFormat.dateTimeParser.parseDateTime(_), _.toString, (key: String, e: _root_.java.lang.Exception) => s"Error parsing date time $key. Example: 2014-04-29T11:56:52Z"
    )

    // Type: date-iso8601
    implicit val pathBindableTypeDateIso8601 = new PathBindable.Parsing[org.joda.time.LocalDate](
      ISODateTimeFormat.yearMonthDay.parseLocalDate(_), _.toString, (key: String, e: _root_.java.lang.Exception) => s"Error parsing date $key. Example: 2014-04-29"
    )

    implicit val queryStringBindableTypeDateIso8601 = new QueryStringBindable.Parsing[org.joda.time.LocalDate](
      ISODateTimeFormat.yearMonthDay.parseLocalDate(_), _.toString, (key: String, e: _root_.java.lang.Exception) => s"Error parsing date $key. Example: 2014-04-29"
    )

    // Enum: EventType
    private[this] val enumEventTypeNotFound = (key: String, e: _root_.java.lang.Exception) => s"Unrecognized $key, should be one of ${speedwing.pagerduty.api.v0.models.EventType.all.mkString(", ")}"

    implicit val pathBindableEnumEventType = new PathBindable.Parsing[speedwing.pagerduty.api.v0.models.EventType] (
      EventType.fromString(_).get, _.toString, enumEventTypeNotFound
    )

    implicit val queryStringBindableEnumEventType = new QueryStringBindable.Parsing[speedwing.pagerduty.api.v0.models.EventType](
      EventType.fromString(_).get, _.toString, enumEventTypeNotFound
    )

  }

}


package speedwing.pagerduty.api.v0 {

  object Constants {

    val BaseUrl = "https://events.pagerduty.com"
    val Namespace = "speedwing.pagerduty.api.v0"
    val UserAgent = "apidoc:0.11.76 http://www.apidoc.me/speedwing/pagerduty-api/0.0.1/play_2_5_client"
    val Version = "0.0.1"
    val VersionMajor = 0

  }

  class Client(
    ws: play.api.libs.ws.WSClient,
    val baseUrl: String = "https://events.pagerduty.com",
    auth: scala.Option[speedwing.pagerduty.api.v0.Authorization] = None,
    defaultHeaders: Seq[(String, String)] = Nil
  ) extends interfaces.Client {
    import speedwing.pagerduty.api.v0.models.json._

    private[this] val logger = play.api.Logger("speedwing.pagerduty.api.v0.Client")

    logger.info(s"Initializing speedwing.pagerduty.api.v0.Client for url $baseUrl")

    def createEvents: CreateEvents = CreateEvents

    object CreateEvents extends CreateEvents {
      override def post(
        createEvent: speedwing.pagerduty.api.v0.models.CreateEvent,
        requestHeaders: Seq[(String, String)] = Nil
      )(implicit ec: scala.concurrent.ExecutionContext): scala.concurrent.Future[speedwing.pagerduty.api.v0.models.Result] = {
        val payload = play.api.libs.json.Json.toJson(createEvent)

        _executeRequest("POST", s"/generic/2010-04-15/create_event.json", body = Some(payload), requestHeaders = requestHeaders).map {
          case r if r.status == 200 => _root_.speedwing.pagerduty.api.v0.Client.parseJson("speedwing.pagerduty.api.v0.models.Result", r, _.validate[speedwing.pagerduty.api.v0.models.Result])
          case r => throw new speedwing.pagerduty.api.v0.errors.FailedRequest(r.status, s"Unsupported response code[${r.status}]. Expected: 200")
        }
      }
    }

    def _requestHolder(path: String): play.api.libs.ws.WSRequest = {

      val holder = ws.url(baseUrl + path).withHeaders(
        "User-Agent" -> Constants.UserAgent,
        "X-Apidoc-Version" -> Constants.Version,
        "X-Apidoc-Version-Major" -> Constants.VersionMajor.toString
      ).withHeaders(defaultHeaders : _*)
      auth.fold(holder) {
        case Authorization.Basic(username, password) => {
          holder.withAuth(username, password.getOrElse(""), play.api.libs.ws.WSAuthScheme.BASIC)
        }
        case a => sys.error("Invalid authorization scheme[" + a.getClass + "]")
      }
    }

    def _logRequest(method: String, req: play.api.libs.ws.WSRequest)(implicit ec: scala.concurrent.ExecutionContext): play.api.libs.ws.WSRequest = {
      val queryComponents = for {
        (name, values) <- req.queryString
        value <- values
      } yield s"$name=$value"
      val url = s"${req.url}${queryComponents.mkString("?", "&", "")}"
      auth.fold(logger.info(s"curl -X $method $url")) { _ =>
        logger.info(s"curl -X $method -u '[REDACTED]:' $url")
      }
      req
    }

    def _executeRequest(
      method: String,
      path: String,
      queryParameters: Seq[(String, String)] = Nil,
      requestHeaders: Seq[(String, String)] = Nil,
      body: Option[play.api.libs.json.JsValue] = None
    )(implicit ec: scala.concurrent.ExecutionContext): scala.concurrent.Future[play.api.libs.ws.WSResponse] = {
      method.toUpperCase match {
        case "GET" => {
          _logRequest("GET", _requestHolder(path).withHeaders(requestHeaders:_*).withQueryString(queryParameters:_*)).get()
        }
        case "POST" => {
          _logRequest("POST", _requestHolder(path).withHeaders(_withJsonContentType(requestHeaders):_*).withQueryString(queryParameters:_*)).post(body.getOrElse(play.api.libs.json.Json.obj()))
        }
        case "PUT" => {
          _logRequest("PUT", _requestHolder(path).withHeaders(_withJsonContentType(requestHeaders):_*).withQueryString(queryParameters:_*)).put(body.getOrElse(play.api.libs.json.Json.obj()))
        }
        case "PATCH" => {
          _logRequest("PATCH", _requestHolder(path).withHeaders(requestHeaders:_*).withQueryString(queryParameters:_*)).patch(body.getOrElse(play.api.libs.json.Json.obj()))
        }
        case "DELETE" => {
          _logRequest("DELETE", _requestHolder(path).withHeaders(requestHeaders:_*).withQueryString(queryParameters:_*)).delete()
        }
         case "HEAD" => {
          _logRequest("HEAD", _requestHolder(path).withHeaders(requestHeaders:_*).withQueryString(queryParameters:_*)).head()
        }
         case "OPTIONS" => {
          _logRequest("OPTIONS", _requestHolder(path).withHeaders(requestHeaders:_*).withQueryString(queryParameters:_*)).options()
        }
        case _ => {
          _logRequest(method, _requestHolder(path).withHeaders(requestHeaders:_*).withQueryString(queryParameters:_*))
          sys.error("Unsupported method[%s]".format(method))
        }
      }
    }

    /**
     * Adds a Content-Type: application/json header unless the specified requestHeaders
     * already contain a Content-Type header
     */
    def _withJsonContentType(headers: Seq[(String, String)]): Seq[(String, String)] = {
      headers.find { _._1.toUpperCase == "CONTENT-TYPE" } match {
        case None => headers ++ Seq(("Content-Type" -> "application/json; charset=UTF-8"))
        case Some(_) => headers
      }
    }

  }

  object Client {

    def parseJson[T](
      className: String,
      r: play.api.libs.ws.WSResponse,
      f: (play.api.libs.json.JsValue => play.api.libs.json.JsResult[T])
    ): T = {
      f(play.api.libs.json.Json.parse(r.body)) match {
        case play.api.libs.json.JsSuccess(x, _) => x
        case play.api.libs.json.JsError(errors) => {
          throw new speedwing.pagerduty.api.v0.errors.FailedRequest(r.status, s"Invalid json for class[" + className + "]: " + errors.mkString(" "))
        }
      }
    }

  }

  sealed trait Authorization
  object Authorization {
    case class Basic(username: String, password: Option[String] = None) extends Authorization
  }

  package interfaces {

    trait Client {
      def baseUrl: String
      def createEvents: speedwing.pagerduty.api.v0.CreateEvents
    }

  }

  trait CreateEvents {
    /**
     * Create an alert on Pagerduty
     */
    def post(
      createEvent: speedwing.pagerduty.api.v0.models.CreateEvent,
      requestHeaders: Seq[(String, String)] = Nil
    )(implicit ec: scala.concurrent.ExecutionContext): scala.concurrent.Future[speedwing.pagerduty.api.v0.models.Result]
  }

  package errors {

    case class FailedRequest(responseCode: Int, message: String, requestUri: Option[_root_.java.net.URI] = None) extends _root_.java.lang.Exception(s"HTTP $responseCode: $message")

  }

}